name: Build Docker Image

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]

jobs:
  docker:
    name: Build i push Docker image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout kod
        uses: actions/checkout@v3
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login na Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build i push backend
        uses: docker/build-push-action@v4
        with:
          context: ./forum
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/planinarski-forum-backend:latest
      
      - name: Build i push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/planinarski-forum-frontend:latest